//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescueLink.Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RescueLink.Application.Localization.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use..
        /// </summary>
        public static string AuthenticationEmailAlreadyInUse {
            get {
                return ResourceManager.GetString("AuthenticationEmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string AuthenticationInvalidCredentials {
            get {
                return ResourceManager.GetString("AuthenticationInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is invalid or has expired..
        /// </summary>
        public static string AuthenticationInvalidRefreshToken {
            get {
                return ResourceManager.GetString("AuthenticationInvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is not authenticated..
        /// </summary>
        public static string AuthenticationUnauthenticated {
            get {
                return ResourceManager.GetString("AuthenticationUnauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to modify this pet report..
        /// </summary>
        public static string PetReportForbidden {
            get {
                return ResourceManager.GetString("PetReportForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is not a valid JPEG, PNG or WebP image..
        /// </summary>
        public static string PetReportInvalidPhotoFile {
            get {
                return ResourceManager.GetString("PetReportInvalidPhotoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pet report can contain at most {0} photos..
        /// </summary>
        public static string PetReportMaximumPhotoCountReached {
            get {
                return ResourceManager.GetString("PetReportMaximumPhotoCountReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active pet reports can be modified..
        /// </summary>
        public static string PetReportNotActive {
            get {
                return ResourceManager.GetString("PetReportNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pet report was not found..
        /// </summary>
        public static string PetReportNotFound {
            get {
                return ResourceManager.GetString("PetReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo was not found in this pet report..
        /// </summary>
        public static string PetReportPhotoNotFound {
            get {
                return ResourceManager.GetString("PetReportPhotoNotFound", resourceCulture);
            }
        }
    }
}
